controllers:
    resource: ../src/Controller/
    type: attribute

todo:
    path: /todo
    controller: App\Controller\TodoController

homepage:
    path: /
    controller: App\Controller\HomepageController